export const FETCH_BOOKS_SUCCESS = '@FETCH_BOOKS_SUCCESS';
export const FETCH_LATEST_BOOKS_SUCCESS = '@FETCH_LATEST_BOOKS_SUCCESS';
export const FETCH_DETAIL_BOOKS_SUCCESS = '@FETCH_DETAIL_BOOKS_SUCCESS';
export const LOGIN_ACCOUNT = '@LOGIN_ACCOUNT';
export const GET_NAME = '@GET_NAME';
export const GET_TOKEN = '@GET_TOKEN';
